<?php use \LightnCandy\SafeString as SafeString;use \LightnCandy\Runtime as LR;return function ($in = null, $options = null) {
    $helpers = array(            'svgicon' => function($name, $color, $size) {
                $icons = array();
                $icons['download-icon1'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M400 200c0 112-89 200-201 200C88 400 0 311 0 199S89 0 201 0c111 0 199 89 199 200zm-179-8l-3-1V89c0-15-7-24-18-23-13 1-18 9-18 22v107l-34-35c-8-8-18-11-27-2-8 8-7 18 2 26l63 63c10 11 18 10 28 0l63-62c8-8 10-17 2-27-7-8-17-7-27 2l-31 32zm-21 113h82c13 0 24-4 32-14 10-14 8-29 6-44-1-4-8-9-12-8-5 0-9 6-12 10-2 3-1 8 0 13 1 13-5 17-18 17H131c-25 0-25 0-26-25-1-3 0-6-2-7-3-4-8-8-12-8s-10 5-11 9c-11 30 8 57 40 57h80z"/></g></svg>';
                $icons['download-icon2'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M45 355h310v-65c1-16 15-27 29-22 9 3 16 11 16 20v91c0 12-10 21-24 21H26c-17 0-26-9-26-26v-85a22 22 0 0143-8 31 31 0 011 11l1 57z"/><path data-name="Path 1270" d="M222 235l5-5 45-45c9-9 23-9 32 0s9 22-1 32l-86 86c-10 10-23 10-34 0l-86-86a22 22 0 1131-31l45 44a55 55 0 013 4l2-1V24c0-13 8-23 20-24 13-1 24 9 24 23v212z"/></g></svg>';
                $icons['download-icon3'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M200 400H26c-18 0-26-9-26-27v-73c0-16 9-25 24-25h105a14 14 0 018 4l28 28c21 21 48 21 69 0l28-29a13 13 0 018-3h106c14 0 24 9 24 23v79c0 14-10 23-25 23H200zm155-63c-9 0-17 8-17 16a15 15 0 0015 16c9 0 17-7 17-16a16 16 0 00-15-16zm-47 16c0-9-7-16-16-16a16 16 0 00-15 16c0 9 6 16 15 16s16-7 16-16zM245 127h55a56 56 0 017 0c7 0 11 4 13 10 3 6 1 11-3 16l-43 45-62 63c-8 9-17 9-25 1L83 154c-5-5-6-11-4-18 3-7 9-9 15-9h61v-9-99c0-14 5-19 17-19h55c13 0 18 5 18 19v99z"/></g></svg>';
                $icons['download-icon4'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M178 234v-7V24c0-13 8-23 20-24 13-1 24 9 24 23v212l5-5 44-44c10-9 23-10 32-1s9 23-1 33l-85 85c-10 11-23 11-34 0l-85-86a22 22 0 0123-37 28 28 0 018 6l44 44a31 31 0 013 5zM200 400H24c-17 0-28-14-23-29 3-10 12-15 23-16h351c12 0 21 6 24 16 5 15-6 29-22 29H200z"/></g></svg>';
                $icons['preview-icon1'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M200 325c-36 0-70-11-101-30a356 356 0 01-92-80c-9-11-9-19 0-29 37-44 79-79 131-99 51-20 102-14 151 12 41 22 76 52 106 89 6 8 7 16 1 23-39 48-85 85-141 105a167 167 0 01-55 9zm0-47c41 0 75-36 75-81s-34-81-75-81c-42 0-75 36-75 81s34 81 75 81z"/><path d="M200 159c21 0 38 17 38 38 0 20-17 37-38 37s-38-17-38-37c0-21 17-38 38-38z"/></g></svg>';
                $icons['preview-icon2'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M0 195c2-10 9-18 16-26 26-28 54-52 89-70a203 203 0 01202 6c33 20 61 46 86 75 3 4 5 10 7 15v10c-2 10-9 18-16 26-24 26-51 50-84 67a206 206 0 01-207-3c-31-18-57-42-81-69-5-6-10-13-12-21zm199 99c30 0 57-8 82-21 33-18 60-43 84-70 2-2 2-4 0-6-21-24-45-47-74-64-27-16-56-26-88-27-28 0-54 6-79 19-35 17-64 43-89 72-2 2-2 4 0 6 21 24 45 47 74 64 27 17 58 27 90 27z"/><path d="M202 276c-45 1-82-32-84-73-2-42 34-77 79-79s83 31 85 74c1 42-34 76-80 78zm-2-30c27-1 49-21 49-46s-22-46-49-45c-27 0-49 20-49 45s22 46 49 46z"/></g></svg>';
                $icons['preview-icon3'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M201 0l12 12 80 76a9 9 0 012 6v98c0 3 1 5 3 6a83 83 0 0133 122l-2 3 61 59-19 18-60-59-15 8-1 3v19H10v-5V4 0zm68 108h-86V25H36v321h176l-2-2a83 83 0 01-33-38c-1-3-3-4-6-4H66v-25h103l5-33H66v-25h121a8 8 0 005-2c19-19 41-29 68-28h9zm-11 225c34 0 62-27 62-59 0-34-28-61-62-61s-62 27-62 59c0 34 27 61 62 61zm-9-250l-40-39v39z"/></g></svg>';
                $icons['preview-icon4'] = '<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 400 400"><g fill="#9a9999"><path d="M0 200V55C0 28 16 8 41 2a63 63 0 0115-2h289c32 0 55 23 55 54v248c0 10-6 16-15 16-8 0-14-6-14-16V56c0-16-11-27-28-27H57c-18 0-28 9-28 28v286c0 19 10 28 28 28h243c11 0 18 6 18 15s-7 14-18 14H56c-28 0-49-16-55-41a67 67 0 01-1-15V200z"/><path d="M314 302l15 15 52 51c7 7 7 14 2 20-6 6-13 5-20-2l-67-65a11 11 0 00-1-1 104 104 0 01-149-26c-29-43-20-99 20-133 39-33 99-31 137 4 38 34 45 93 11 137zm-159-64c-1 42 34 77 77 77 42 1 78-33 78-75 1-42-34-77-75-77-44-1-79 32-80 75z"/></g></svg>';

                $icon = isset($icons[$name]) ? $icons[$name] : '';
                $icon = preg_replace('/fill=\"#[a-z0-9]{3,6}\"/', 'fill="' . $color . '"', $icon);
                $icon = preg_replace('/width=\"[0-9]+\"/', 'width="' . $size . '"', $icon);
                $icon = preg_replace('/height=\"[0-9].\"/', 'height="' . $size . '"', $icon);

                return $icon;
            },
            'xif' => function($param, $second, $options) {
                if ($param === $second) {
                    return $options['fn']();
                } else {
                    return $options['inverse']();
                }
            },
            'xunless' => function($param, $second, $options) {
                if ($param !== $second) {
                    return $options['fn']();
                } else {
                    return $options['inverse']();
                }
            },
);
    $partials = array();
    $cx = array(
        'flags' => array(
            'jstrue' => false,
            'jsobj' => false,
            'jslen' => false,
            'spvar' => true,
            'prop' => false,
            'method' => false,
            'lambda' => false,
            'mustlok' => false,
            'mustlam' => false,
            'mustsec' => false,
            'echo' => false,
            'partnc' => false,
            'knohlp' => false,
            'debug' => isset($options['debug']) ? $options['debug'] : 1,
        ),
        'constants' => array(),
        'helpers' => isset($options['helpers']) ? array_merge($helpers, $options['helpers']) : $helpers,
        'partials' => isset($options['partials']) ? array_merge($partials, $options['partials']) : $partials,
        'scopes' => array(),
        'sp_vars' => isset($options['data']) ? array_merge(array('root' => $in), $options['data']) : array('root' => $in),
        'blparam' => array(),
        'partialid' => 0,
        'runtime' => '\LightnCandy\Runtime',
    );
    
    $inary=is_array($in);
    return '<div class="wpfd-single-file">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['icon'])) ? $in['settings']['icon'] : null), false)) ? '    <div class="wpfd-single-file--icon">
'.LR::hbbch($cx, 'xunless', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['link_on_icon'])) ? $in['settings']['link_on_icon'] : null),'none'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '            <a href="'.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['link_on_icon'])) ? $in['settings']['link_on_icon'] : null),'preview'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['openpdflink'])) ? $in['file']['openpdflink'] : null), false)) ? ''.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['openpdflink'])) ? $in['file']['openpdflink'] : null)).'' : ''.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['viewerlink'])) ? $in['file']['viewerlink'] : null)).'').'';}).''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['link_on_icon'])) ? $in['settings']['link_on_icon'] : null),'download'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return ''.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['linkdownload'])) ? $in['file']['linkdownload'] : null)).'';}).'" alt="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['crop_title'])) ? $in['file']['crop_title'] : null)).'" class="'.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['link_on_icon'])) ? $in['settings']['link_on_icon'] : null),'preview'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return 'wpfdlightbox';}, function($cx, $in) {$inary=is_array($in);return 'noLightbox';}).'">
';}).'            <div class="wpfd-icon-placeholder" style="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['icon_style'])) ? $in['file']['icon_style'] : null)).'"></div>
        '.LR::hbbch($cx, 'xunless', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['link_on_icon'])) ? $in['settings']['link_on_icon'] : null),'none'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '</a>';}).'
    </div>
' : '').'
    <div class="wpfd-single-file--details wpfd-file-content">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_title'])) ? $in['settings']['file_title'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['crop_title'])) ? $in['file']['crop_title'] : null), false)) ? '                <'.LR::encq($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['title_wrapper_tag'])) ? $in['settings']['title_wrapper_tag'] : null)).' class="wpfd-file-content--title">'.LR::raw($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['crop_title'])) ? $in['file']['crop_title'] : null)).'</'.LR::encq($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['title_wrapper_tag'])) ? $in['settings']['title_wrapper_tag'] : null)).'>
' : '').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_description'])) ? $in['settings']['file_description'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['description'])) ? $in['file']['description'] : null), false)) ? '                <p class="wpfd-file-content--description">
                    '.LR::raw($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['description'])) ? $in['file']['description'] : null)).'
                </p>
' : '').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_information'])) ? $in['settings']['file_information'] : null), false)) ? '        <div class="wpfd-file-content--meta">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_size'])) ? $in['settings']['file_size'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['size'])) ? $in['file']['size'] : null), false)) ? '                    <div>File size: '.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['size'])) ? $in['file']['size'] : null)).'</div>
' : '').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_created_date'])) ? $in['settings']['file_created_date'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['created'])) ? $in['file']['created'] : null), false)) ? '                    <div>Created: '.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['created'])) ? $in['file']['created'] : null)).'</div>
' : '').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_update_date'])) ? $in['settings']['file_update_date'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['modified'])) ? $in['file']['modified'] : null), false)) ? '                    <div>Updated: '.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['modified'])) ? $in['file']['modified'] : null)).'</div>
' : '').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_download_hit'])) ? $in['settings']['file_download_hit'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['hits'])) ? $in['file']['hits'] : null), false)) ? '                    <div>Hits: '.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['hits'])) ? $in['file']['hits'] : null)).'</div>
' : '').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['file_version'])) ? $in['settings']['file_version'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['version'])) ? $in['file']['version'] : null), false)) ? '                    <div>Version: '.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['version'])) ? $in['file']['version'] : null)).'</div>
' : '').'' : '').'        </div>
' : '').'    </div>
    <div class="wpfd-single-file--buttons">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_button'])) ? $in['settings']['download_button'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['show_add_to_cart'])) ? $in['file']['show_add_to_cart'] : null), false)) ? '                <a class="wpfd_single_add_to_cart wpfd-single-file-button wpfd-button-download wpfd_downloadlink" href="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['linkdownload'])) ? $in['file']['linkdownload'] : null)).'"'.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['product_id'])) ? $in['file']['product_id'] : null), false)) ? ' data-product_id="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['product_id'])) ? $in['file']['product_id'] : null)).'"' : '').'>
                    <i style="font-size: '.LR::encq($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_size'])) ? $in['settings']['download_icon_size'] : null)).'px;" class="zmdi zmdi-shopping-cart-plus wpfd-add-to-cart"></i>
                    <span>Add to cart</span>
                </a>
' : '                                <a href="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['linkdownload'])) ? $in['file']['linkdownload'] : null)).'"  data-id="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['ID'])) ? $in['file']['ID'] : null)).'" title="'.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['description'])) ? $in['file']['description'] : null), false)) ? ''.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['description'])) ? $in['file']['description'] : null)).'' : ''.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['title'])) ? $in['file']['title'] : null)).'').'" class="noLightbox wpfd_downloadlink wpfd-single-file-button wpfd-button-download">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_active'])) ? $in['settings']['download_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_position'])) ? $in['settings']['download_icon_position'] : null),'left'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                    '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon'])) ? $in['settings']['download_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_color'])) ? $in['settings']['download_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_size'])) ? $in['settings']['download_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                    <span>Download</span>
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_active'])) ? $in['settings']['download_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_position'])) ? $in['settings']['download_icon_position'] : null),'right'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                    '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon'])) ? $in['settings']['download_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_color'])) ? $in['settings']['download_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['download_icon_size'])) ? $in['settings']['download_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                </a>
').'' : '').''.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_button'])) ? $in['settings']['preview_button'] : null), false)) ? ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['show_add_to_cart'])) ? $in['file']['show_add_to_cart'] : null), false)) ? '                <a class="wpfd-single-file-button wpfd-button-preview wpfd_single_view_product" href="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['viewerlink'])) ? $in['file']['viewerlink'] : null)).'" target="_blank">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_active'])) ? $in['settings']['preview_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_position'])) ? $in['settings']['preview_icon_position'] : null),'left'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                    '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon'])) ? $in['settings']['preview_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_color'])) ? $in['settings']['preview_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_size'])) ? $in['settings']['preview_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                    <span>View product</span>
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_active'])) ? $in['settings']['preview_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_position'])) ? $in['settings']['preview_icon_position'] : null),'right'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                    '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon'])) ? $in['settings']['preview_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_color'])) ? $in['settings']['preview_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_size'])) ? $in['settings']['preview_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                </a>
' : ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['openpdflink'])) ? $in['file']['openpdflink'] : null), false)) ? '                    <a href="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['openpdflink'])) ? $in['file']['openpdflink'] : null)).'" class="wpfd-single-file-button wpfd-button-preview'.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['open_in_lightbox'])) ? $in['file']['open_in_lightbox'] : null), false)) ? ' wpfdlightbox' : '').'"'.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['open_in_newtab'])) ? $in['file']['open_in_newtab'] : null), false)) ? ' target="_blank"' : '').'>
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_active'])) ? $in['settings']['preview_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_position'])) ? $in['settings']['preview_icon_position'] : null),'left'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                        '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon'])) ? $in['settings']['preview_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_color'])) ? $in['settings']['preview_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_size'])) ? $in['settings']['preview_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                        <span>Preview</span>
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_active'])) ? $in['settings']['preview_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_position'])) ? $in['settings']['preview_icon_position'] : null),'right'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                        '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon'])) ? $in['settings']['preview_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_color'])) ? $in['settings']['preview_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_size'])) ? $in['settings']['preview_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                    </a>
' : ''.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['viewerlink'])) ? $in['file']['viewerlink'] : null), false)) ? '                        <a href="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['viewerlink'])) ? $in['file']['viewerlink'] : null)).'" class="wpfd-single-file-button wpfd-button-preview wpfd_previewlink'.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['open_in_lightbox'])) ? $in['file']['open_in_lightbox'] : null), false)) ? ' wpfdlightbox' : '').'"'.((LR::ifvar($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['open_in_newtab'])) ? $in['file']['open_in_newtab'] : null), false)) ? ' target="_blank"' : '').'
                            data-id="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['ID'])) ? $in['file']['ID'] : null)).'" data-catid="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['catid'])) ? $in['file']['catid'] : null)).'"
                            data-file-type="'.LR::encq($cx, ((isset($in['file']) && is_array($in['file']) && isset($in['file']['ext'])) ? $in['file']['ext'] : null)).'">
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_active'])) ? $in['settings']['preview_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_position'])) ? $in['settings']['preview_icon_position'] : null),'left'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                            '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon'])) ? $in['settings']['preview_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_color'])) ? $in['settings']['preview_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_size'])) ? $in['settings']['preview_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                            <span>Preview</span>
'.((LR::ifvar($cx, ((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_active'])) ? $in['settings']['preview_icon_active'] : null), false)) ? ''.LR::hbbch($cx, 'xif', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_position'])) ? $in['settings']['preview_icon_position'] : null),'right'),array()), $in, false, function($cx, $in) {$inary=is_array($in);return '                            '.LR::raw($cx, LR::hbch($cx, 'svgicon', array(array(((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon'])) ? $in['settings']['preview_icon'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_color'])) ? $in['settings']['preview_icon_color'] : null),((isset($in['settings']) && is_array($in['settings']) && isset($in['settings']['preview_icon_size'])) ? $in['settings']['preview_icon_size'] : null)),array()), 'raw', $in)).'
';}).'' : '').'                        </a>
' : '').'').'').'' : '').'    </div>
</div>
';
};?>